apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: capb7-controller-manager-pdb
  namespace: capb7-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      control-plane: controller-manager
      deployment-size: extra-large 