apiVersion: v1
kind: Service
metadata:
  name: beskar7-webhook-service
  namespace: beskar7-system
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    control-plane: controller-manager 