apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See ../small/kustomization.yaml for what a size overlay may change.
namespace: capb7-system

resources:
- ../../default

patches:
- path: manager_patch.yaml

labels:
- pairs:
    deployment-size: large
  includeSelectors: false
