apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capb7-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: capb7-system/capb7-serving-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: capb7-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: capb7-system/capb7-serving-cert 