apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beskar7-system

resources:
- ../../default

patches:
- path: manager_patch.yaml

namePrefix: small-

labels:
- pairs:
    deployment-size: small
  includeSelectors: true 