apiVersion: apps/v1
kind: Deployment
metadata:
  name: capb7-controller-manager
  namespace: capb7-system
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 50Mi
