apiVersion: v2
name: beskar7
description: A Helm chart for Beskar7 - Cluster API Infrastructure Provider for Immutable Bare Metal
type: application
version: 0.4.0-alpha.2
appVersion: "v0.4.0-alpha.2"
keywords:
  - cluster-api
  - infrastructure
  - bare-metal
  - redfish
  - kubernetes
home: https://github.com/projectbeskar/beskar7
sources:
  - https://github.com/projectbeskar/beskar7
maintainers:
  - name: projectbeskar
    url: https://github.com/projectbeskar
annotations:
  category: Infrastructure
