# This kustomization.yaml is not intended to be run directly,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_beskar7clusters.yaml
- bases/infrastructure.cluster.x-k8s.io_beskar7machines.yaml
- bases/infrastructure.cluster.x-k8s.io_beskar7machinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_physicalhosts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_beskar7clusters.yaml
- path: patches/webhook_in_beskar7machines.yaml
- path: patches/webhook_in_beskar7machinetemplates.yaml
- path: patches/webhook_in_physicalhosts.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_beskar7clusters.yaml
- path: patches/cainjection_in_beskar7machines.yaml
- path: patches/cainjection_in_beskar7machinetemplates.yaml
- path: patches/cainjection_in_physicalhosts.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

labels:
- pairs:
    cluster.x-k8s.io/contract: v1beta1
    cluster.x-k8s.io/provider: beskar7
  includeSelectors: true 