/*
Copyright 2024 The Beskar7 Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package contract

import (
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"
)

// webhookMarkerPath pulls the path= value out of a +kubebuilder:webhook marker.
var webhookMarkerPath = regexp.MustCompile(`\+kubebuilder:webhook:(?:.*,)?path=([^,\s]+)`)

// templatePathLine matches the `path:` line of a clientConfig.service block in
// the Helm chart's webhook template. The template only becomes YAML once
// rendered, but its path lines are literal, so a line scan is enough.
var templatePathLine = regexp.MustCompile(`^\s*path:\s*(\S+)\s*$`)

// yamlDocumentSeparator splits a multi-document YAML file.
var yamlDocumentSeparator = regexp.MustCompile(`(?m)^---\s*$`)

// TestWebhookConfigurationsMatchServedPaths pins the webhook paths the
// kustomize overlay (config/webhook/manifests.yaml) and the Helm chart
// (charts/beskar7/templates/webhook-configuration.yaml) register to the
// +kubebuilder:webhook markers under api/, which sit next to the handlers the
// manager serves (cmd/manager/main.go registers webhooks.Beskar7ClusterWebhook
// and nothing else).
//
// A registered path with no handler behind it is not inert: the webhooks are
// failurePolicy: Fail, the webhook server answers 404, and the API server
// rejects every create/update of that kind. Until v0.4.5 the kustomize file
// still declared mutate/validate entries for Beskar7Machine and
// Beskar7MachineTemplate that no Go code served, so a kustomize or
// single-file-manifest install could not create a single Beskar7Machine. Helm
// never hit it because the chart only ever declared the Beskar7Cluster pair,
// which is also why the Helm-based E2E stayed green. The kustomize file is
// generated by `make manifests` now; the chart copy is still hand-maintained.
//
// Both files are checked in both directions — a declared path needs a marker,
// and a marker needs to be declared — so a new webhook cannot ship in one
// install path but not the other. Scanning the markers instead of hardcoding
// the two Beskar7Cluster paths keeps the test valid across the api/v1beta1 →
// api/v1beta2 rename: the version is part of the path.
func TestWebhookConfigurationsMatchServedPaths(t *testing.T) {
	served := servedWebhookPaths(t)

	t.Run("kustomize", func(t *testing.T) {
		declared := kustomizeWebhookPaths(t, filepath.Join("..", "..", "config", "webhook", "manifests.yaml"))
		assertSamePaths(t, declared, served)
	})
	t.Run("helm-chart", func(t *testing.T) {
		declared := templateWebhookPaths(t, filepath.Join("..", "..", "charts", "beskar7", "templates", "webhook-configuration.yaml"))
		assertSamePaths(t, declared, served)
	})
}

// servedWebhookPaths returns the path= of every +kubebuilder:webhook marker in
// the non-test Go files under api/, mapped to the file that declares it.
func servedWebhookPaths(t *testing.T) map[string]string {
	t.Helper()
	repoRoot := filepath.Join("..", "..")
	apiRoot := filepath.Join(repoRoot, "api")
	served := map[string]string{}
	err := filepath.WalkDir(apiRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
			return nil
		}
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(repoRoot, p)
		if err != nil {
			return err
		}
		for _, m := range webhookMarkerPath.FindAllStringSubmatch(string(raw), -1) {
			served[m[1]] = rel
		}
		return nil
	})
	if err != nil {
		t.Fatalf("scanning %s for +kubebuilder:webhook markers: %v", apiRoot, err)
	}
	if len(served) == 0 {
		t.Fatalf("no +kubebuilder:webhook markers found under %s — did the webhooks package move?", apiRoot)
	}
	return served
}

// kustomizeWebhookPaths parses the generated kustomize webhook manifest and
// returns the clientConfig.service.path of every webhook it declares, mapped
// to "<Kind>/<webhook name>" for the failure message.
func kustomizeWebhookPaths(t *testing.T, file string) map[string]string {
	t.Helper()
	raw, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	declared := map[string]string{}
	for _, doc := range yamlDocumentSeparator.Split(string(raw), -1) {
		if strings.TrimSpace(doc) == "" {
			continue
		}
		var cfg struct {
			Kind     string `json:"kind"`
			Webhooks []struct {
				Name         string `json:"name"`
				ClientConfig struct {
					Service struct {
						Path string `json:"path"`
					} `json:"service"`
				} `json:"clientConfig"`
			} `json:"webhooks"`
		}
		if err := yaml.Unmarshal([]byte(doc), &cfg); err != nil {
			t.Fatalf("%s: %v", file, err)
		}
		if cfg.Kind != "MutatingWebhookConfiguration" && cfg.Kind != "ValidatingWebhookConfiguration" {
			t.Fatalf("%s: unexpected document kind %q", file, cfg.Kind)
		}
		for _, w := range cfg.Webhooks {
			if w.ClientConfig.Service.Path == "" {
				t.Errorf("%s: webhook %q has no clientConfig.service.path", filepath.Base(file), w.Name)
				continue
			}
			declared[w.ClientConfig.Service.Path] = cfg.Kind + "/" + w.Name
		}
	}
	if len(declared) == 0 {
		t.Fatalf("%s: declares no webhooks", file)
	}
	return declared
}

// templateWebhookPaths scans the chart's webhook template for its literal
// `path:` lines and maps each path to its file:line for the failure message.
func templateWebhookPaths(t *testing.T, file string) map[string]string {
	t.Helper()
	raw, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	declared := map[string]string{}
	for i, line := range strings.Split(string(raw), "\n") {
		if m := templatePathLine.FindStringSubmatch(line); m != nil {
			declared[m[1]] = fmt.Sprintf("%s:%d", filepath.Base(file), i+1)
		}
	}
	if len(declared) == 0 {
		t.Fatalf("%s: no `path:` lines found — has the template been restructured?", file)
	}
	return declared
}

// assertSamePaths fails on any path declared without a marker (the manager
// would answer 404, blocking every create/update of that kind) and on any
// marker left undeclared (the handler would never be called on that install
// path).
func assertSamePaths(t *testing.T, declared, served map[string]string) {
	t.Helper()
	for _, p := range slices.Sorted(maps.Keys(declared)) {
		if _, ok := served[p]; !ok {
			t.Errorf("%s declares %s, but no +kubebuilder:webhook marker (and so no handler) serves it; "+
				"with failurePolicy: Fail every create/update of that resource is rejected with a 404 from the webhook server",
				declared[p], p)
		}
	}
	for _, p := range slices.Sorted(maps.Keys(served)) {
		if _, ok := declared[p]; !ok {
			t.Errorf("%s has a +kubebuilder:webhook marker for %s, but the manifest does not register it", served[p], p)
		}
	}
}
